name: OnPushNewVersion

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Checkout stserver
        uses: actions/checkout@v2
        with:
          repository: impleotv/stserver2
          token: ${{ secrets.TOKEN }}
          path: ./stserver2
 
      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      
      - name: Copy CHANGELOG.md from stserver2
        run: |
          cp ./stserver2/CHANGELOG.md ./CHANGELOG-SERVER.md 
          rm -rf ./stserver2

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      - name: Setup NodeJs 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}       
      - name: Generate README file
        run: node index.js ${{env.RELEASE_VERSION }}

      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -name: Create release    
        uses: ncipollo/release-action@v1
        with:
          artifacts: "CHANGELOG.md,CHANGELOG-SERVER.md "       
          token: ${{ secrets.GITHUB_TOKEN }}
        